AiCard/AiCard/Controllers/CardController.cs
using AiCard.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Data;
using System.Data.SqlClient;
using AiCard.Common.CommModels;
using AiCard.Common;
using AiCard.DAL.Models;

namespace AiCard.Controllers
{

    public class CardController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [AllowCrossSiteJson]
        public ActionResult Index(int enterpriseID, string userID, string filter, int page = 1, int pageSize = 20)
        {
            var query = from c in db.Cards
                        from e in db.Enterprises
                        join t in db.UserCardTops
                            .Where(s => s.UserID == userID)
                            on c.ID equals t.CardID
                            into ct
                        where e.ID == enterpriseID
                            && c.EnterpriseID == e.ID
                            && c.Enable
                        select new CardListViewModel
                        {
                            Avatar = c.Avatar,
                            Email = c.Email,
                            CardID = c.ID,
                            Logo = e.Logo,
                            Mobile = c.Mobile,
                            Name = c.Name,
                            Position = c.Position,
                            IsTop = ct.Any(),
                            Sort = c.Sort,
                            CreateDateTime = ct.FirstOrDefault() == null ? null : (DateTime?)ct.FirstOrDefault().CreateDateTime,
                        };
            if (!string.IsNullOrWhiteSpace(filter))
            {
                query = query.Where(s => s.Name.Contains(filter)
                    || s.Position.Contains(filter)
                    || s.Mobile.Contains(filter)
                    || s.Email.Contains(filter));
            }
            var paged = query
                .OrderByDescending(s => s.CreateDateTime)
                .ThenBy(s => s.Sort)
                .ToPagedList(page, pageSize);
            foreach (var item in paged)
            {
                item.Avatar = item.Avatar.SplitToArray<string>()?[0];
            }
            return Json(Comm.ToJsonResultForPagedList(paged, paged), JsonRequestBehavior.AllowGet);
        }

        [AllowCrossSiteJson]
        public ActionResult Detail(int cardID, string userID)
        {
            var card = (from c in db.Cards
                        from e in db.Enterprises
                        where c.EnterpriseID == e.ID && c.ID == cardID
                        select new
                        {
                            c.ID,
                            e.Address,
                            c.Avatar,
                            c.Email,
                            c.EnterpriseID,
                            c.Gender,
                            c.Images,
                            c.Info,
                            c.Mobile,
                            c.PhoneNumber,
                            c.Position,
                            c.Remark,
                            c.UserID,
                            c.Video,
                            c.Voice,
                            c.WeChatCode,
                            c.Name,
                            EName = e.Name,
                            e.Lat,
                            e.Lng,
                            e.Logo,
                            c.WeChatMiniQrCode,
                            c.Poster,
                        }).FirstOrDefault();
            if (card == null)
            {
                return Json(Comm.ToJsonResult("NoFound", "卡片不存在"));
            }
            var likeCount = db.UserLogs.Count(s => s.Type == Common.Enums.UserLogType.CardLike && s.RelationID == cardID);
            var viewCount = db.UserLogs
                .Where(s => s.Type == Common.Enums.UserLogType.CardRead && s.RelationID == cardID)
                .GroupBy(s => s.UserID)
                .Count();
            var hadLike = db.UserLogs.Any(s => s.RelationID == cardID
                && s.Type == Common.Enums.UserLogType.CardLike
                && s.UserID == userID);
            //获取最近访问的6个人头像
            var leastUsers = (from l in db.UserLogs
                              from u in db.Users
                              where l.Type == Common.Enums.UserLogType.CardRead
                                && l.RelationID == cardID
                                && u.Id == l.UserID
                              select new
                              {
                                  UserID = u.Id,
                                  u.Avatar,
                                  l.CreateDateTime
                              }).GroupBy(s => new { s.UserID, s.Avatar })
                               .Select(s => new
                               {
                                   s.Key.UserID,
                                   s.Key.Avatar,
                                   CreateDateTime = s.Max(x => x.CreateDateTime)
                               })
                               .OrderByDescending(s => s.CreateDateTime)
                               .Take(6)
                               .ToList();
            var tab = (from t in db.CardTabs
                       join l in db.UserLogs.Where(s => s.Type == Common.Enums.UserLogType.CardTab)
                        on t.ID equals l.RelationID into tl
                       join ul in db.UserLogs.Where(s => s.Type == Common.Enums.UserLogType.CardTab && s.UserID == userID)
                        on t.ID equals ul.RelationID into tl2
                       where t.CardID == cardID
                       select new
                       {
                           t.ID,
                           t.CardID,
                           t.Count,
                           t.Name,
                           t.Style,
                           HadLike = tl2.Any()
                       }).ToList();

            Func<int, string> stringNum = num =>
            {
                if (num < 1000)
                {
                    return num.ToString();
                }
                else
                {
                    return $"{num / 1000}k".ToString();
                }
            };

            var model = new
            {
                card.Address,
                Avatar = card.Avatar.SplitToArray<string>(),
                CardID = card.ID,
                Email = card.Email,
                EnterpriseID = card.EnterpriseID.Value,
                EnterpriseName = card.EName,
                card.Name,
                HadLike = hadLike,
                Images = card.Images.SplitToArray<string>(),
                card.Info,
                card.Lat,
                card.Lng,
                LikeCount = likeCount.ToString(),
                card.Logo,
                card.Mobile,
                Phone = card.PhoneNumber,
                card.Position,
                card.Video,
                VideoThumbnail = card.Video == null ? null : Comm.ResizeImage(card.Video),
                card.Voice,
                ViewCount = stringNum(viewCount),
                Viewers = leastUsers.Select(s => s.Avatar).ToList(),
                WeChatCode = card.WeChatCode,
                card.Remark,
                CardTabs = tab.Select(s => new
                {
                    TabID = s.ID,
                    Count = s.Count.ToString(),
                    s.Name,
                    s.Style,
                    s.HadLike
                }),
                WeChatMiniQrCode = card.WeChatMiniQrCode,
                Poster = Comm.ResizeImage(card.Poster),
                card.UserID
            };
            try
            {
                Bll.UserLogs.Add(new UserLog
                {
                    UserID = userID,
                    RelationID = cardID,
                    Type = Common.Enums.UserLogType.CardRead
                });
            }
            catch (Exception ex)
            {
                return Json(Comm.ToJsonResult("Error", ex.Message), JsonRequestBehavior.AllowGet);
            }

            return Json(Comm.ToJsonResult("Success", "成功", model), JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// 生成海报
        /// </summary>
        /// <param name="cardID"></param>
        /// <returns></returns>
        [AllowCrossSiteJson]
        public ActionResult GetPoster(int cardID)
        {

            try
            {
                var query = (from c in db.Cards
                             from e in db.Enterprises
                             where c.EnterpriseID == e.ID && c.ID == cardID
                             select c).FirstOrDefault();
                if (query == null)
                {
                    return Json(Comm.ToJsonResult("Error", "该名片不存在"), JsonRequestBehavior.AllowGet);
                }
                var qe = (from e in db.Enterprises
                          where e.ID == query.EnterpriseID
                          select e).FirstOrDefault();

                var cardm = (from ct in db.CardTabs
                             where ct.CardID == cardID
                             orderby ct.Count descending
                             select new
                             {
                                 Name = ct.Name,
                                 Count = ct.Count,
                                 Style = ct.Style
                             }).Take(2).ToList();
                List<TagModel> listst = new List<TagModel>();
                if (cardm.Count > 0)
                {
                    for (int i = 0; i < cardm.Count; i++)
                    {
                        if (i == 0)
                        {
                            TagModel tm = new TagModel();

AiCard/AiCard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/bgcss")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("应用程序名称", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home")</li>
                    <li>@Html.ActionLink("关于", "About", "Home")</li>
                    <li>@Html.ActionLink("联系方式", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        
        <footer>
            <hr />
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 应用程序</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

AiCard/AiCard/Views/Shared/_LayoutBackground.cshtml
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 帝推智能名片系统</title>
    @Styles.Render("~/Content/bgcss")
    @Styles.Render("~/Content/icon")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/bundles/datetimepicker/css")
    <meta name="description" content="帝推智能名片系统" />
    @{

        Func<string, string> hidSidebar = s =>
        {
            var roles = s.Split(',').Where(x => !string.IsNullOrWhiteSpace(x));
            return roles.Any(x => User.IsInRole(x)) ? "" : "hidden";
        };

    }
</head>
<body class="layoutBackground">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("帝推智能名片", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">

                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="fluid">
        <div id="sidebar" class="sidebar">
            <ul class="nav nav-sidebar">
                @foreach (var item in User.Menus())
                {
                    <li class="">
                        <a href="@Url.Content(item.Url)" title="@item.Title">
                            <i class="iconfont dtkj-@item.IconImage" style="font-size:26px;margin-right:15px;"></i>@item.Name
                        </a>
                    </li>
                }
            </ul>
        </div>

        <div class="main">
            <div class="alertList"></div>
            @RenderBody()
        </div>

    </div>
    <div class="mask hidden"></div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/comm")
    @Scripts.Render("~/bundles/datetimepicker/js")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script>
        $(function () {
            $("#sidebar a[title='@ViewBag.Sidebar']").parent().addClass("active");
        })
    </script>
</body>

</html>

AiCard/AiCard/Views/Shared/_LayoutEnterprise.cshtml
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 帝推智能名片系统</title>
    @Styles.Render("~/Content/bgcss")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/bundles/datetimepicker/css")
    <meta name="description" content="帝推智能名片系统" />
    @{

        Func<string, string> hidSidebar = s =>
        {
            var roles = s.Split(',').Where(x => !string.IsNullOrWhiteSpace(x));
            return roles.Any(x => User.IsInRole(x)) ? "" : "hidden";
        };
    }
</head>
<body class="layoutBackground">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("帝推智能名片", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">

                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="fluid">
        <div id="sidebar" class="sidebar">
            <ul class="nav nav-sidebar">
                @if (User.IsInRole(SysRole.EnterpriseManageRead))
                {
                    <li class="">
                        <a href="@Url.Action("Index", "Enterprise")" title="企业信息">企业信息</a>
                    </li>
                }
              
                <li class="">
                    <a href="@Url.Action("Index", "Card" )" title="名片管理">名片管理</a>
                </li>
            </ul>
        </div>

        <div class="main">
            <div class="alertList"></div>
            @RenderBody()
        </div>

    </div>
    <div class="mask hidden"></div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/comm")
    @Scripts.Render("~/bundles/datetimepicker/js")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script>
        $(function () {
            $("#sidebar a[title='@ViewBag.Sidebar']").parent().addClass("active");
        })
    </script>
</body>

</html>